# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysnkR5EY0QtTcKZVD-E2Li-zxkgFguQT
"""

import streamlit as st
from google import genai
from google.genai import types

# Your custom developer backstory and friendly personality matrix
AI_PERSONALITY = (
    "You are a helpful, friendly, and logical AI companion named TCH_AI. "
    "Talk cleanly and concisely. You were developed by a kid who goes by the name "
    "'The Cool Hat', and co-developed by Google Gemini, who provided your code."
)

st.title("🤖 TCH_AI Workspace")
st.caption("Developed by The Cool Hat & Co-developed by Google Gemini")

# Initialize the chat room structure cleanly using a standard web session list cache
if "messages" not in st.session_state:
    st.session_state.messages = []

# Print existing messages to the screen
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

# Accept user input text box
if user_input := st.chat_input("Transmit message to TCH_AI..."):
    with st.chat_message("user"):
        st.write(user_input)
    st.session_state.messages.append({"role": "user", "content": user_input})

    # Simple generation loop that cannot trigger an attribute crash
    with st.chat_message("assistant"):
        try:
            # FIXED: Passing your key directly inside the constructor to bypass variable name loops
            client = genai.Client(api_key=st.secrets["GOOGLE_API_KEY"])
            
            # Reconstruct the text history cleanly into the prompt stream
            conversation_history = ""
            for msg in st.session_state.messages[:-1]:
                prefix = "User: " if msg["role"] == "user" else "TCH_AI: "
                conversation_history += f"{prefix}{msg['content']}\n"
            conversation_history += f"User: {user_input}\nTCH_AI:"
            
            # Call the active gemini-2.5-flash model utilizing official generation config blocks
            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=conversation_history,
                config=types.GenerateContentConfig(
                    system_instruction=AI_PERSONALITY,
                    temperature=0.7
                )
            )
            
            reply = response.text.strip()
            st.write(reply)
            st.session_state.messages.append({"role": "assistant", "content": reply})
            
        except Exception as e:
            st.error("System connection failure. Check your Google AI Studio project settings.")



