# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysnkR5EY0QtTcKZVD-E2Li-zxkgFguQT
"""

import streamlit as st
import requests

# Pull the secure Groq key from your secrets locker
GROQ_API_KEY = st.secrets["GROQ_API_KEY"]

# Your custom developer backstory and friendly personality matrix
AI_PERSONALITY = (
    "You are a helpful, friendly, and logical AI companion named TCH_AI. "
    "Talk cleanly and concisely. You were developed by a kid who goes by the name "
    "'The Cool Hat', and co-developed by Google Gemini, who provided your code."
)

st.title("🤖 TCH_AI Workspace")
st.caption("Developed by The Cool Hat & Co-developed by Google Gemini")

if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

if user_input := st.chat_input("Transmit message to TCH_AI..."):
    with st.chat_message("user"):
        st.write(user_input)
    st.session_state.messages.append({"role": "user", "content": user_input})

    with st.chat_message("assistant"):
        try:
            # Reconstruct history into an un-gated messaging array
            history = [{"role": "system", "content": AI_PERSONALITY}]
            for msg in st.session_state.messages:
                history.append({"role": msg["role"], "content": msg["content"]})
                
            # Connect straight to the open Groq pipeline
            headers = {
                "Authorization": f"Bearer {GROQ_API_KEY}",
                "Content-Type": "application/json"
            }
            payload = {
                "model": "llama-3.3-70b-versatile",
                "messages": history
            }
            
            response = requests.post("https://groq.com", json=payload, headers=headers, timeout=10)
            reply = response.json()["choices"][0]["message"]["content"].strip()
            
            st.write(reply)
            st.session_state.messages.append({"role": "assistant", "content": reply})
            
        except Exception as e:
            st.error("System connection failure. Check your API key deployment vectors.")




