# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysnkR5EY0QtTcKZVD-E2Li-zxkgFguQT
"""

import streamlit as st
import requests

# Your custom developer origin story and friendly personality matrix
AI_PERSONALITY = (
    "You are a helpful, friendly, and logical AI companion named TCH_AI. "
    "Talk cleanly and concisely. You were developed by a kid who goes by the name "
    "'The Cool Hat', and co-developed by Google Gemini, who provided your code."
)

st.set_page_config(page_title="TCH_AI Interface", page_icon="🤖")
st.title("🤖 TCH_AI Workspace")
st.caption("Synchronized permanent connection pipeline operational.")

# Initialize the messaging memory list array cleanly
if "messages_log" not in st.session_state:
    st.session_state.messages_log = []

# Render the historical conversation text blocks onto the web app screen
for message in st.session_state.messages_log:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Accept user inputs via the terminal input box component
if user_input := st.chat_input("Transmit message to TCH_AI...", key="tch_chat_box"):
    with st.chat_message("user"):
        st.markdown(user_input)
    st.session_state.messages_log.append({"role": "user", "content": user_input})
        
    with st.chat_message("assistant"):
        try:
            # We route the prompt package through a clean, unblocked public engine link
            API_URL = "https://chateverywhere.app"
            
            # Format the historical list precisely for the open endpoint engine
            formatted_messages = [{"role": "system", "content": AI_PERSONALITY}]
            for msg in st.session_state.messages_log:
                formatted_messages.append({"role": msg["role"], "content": msg["content"]})
                
            payload = {
                "model": "gpt-4o-mini",
                "messages": formatted_messages
            }
            
            response = requests.post(API_URL, json=payload, timeout=12)
            
            if response.status_code == 200:
                reply_text = response.text.strip()
                st.markdown(reply_text)
                st.session_state.messages_log.append({"role": "assistant", "content": reply_text})
            else:
                st.error(f"Network node status check required (Code {response.status_code}).")
                
        except Exception as e:
            st.error("System connection failure. Open pipeline routing disrupted.")


